services:
  - type: web
    name: post-reminder
    env: python
    buildCommand: pip install -r desktop_app/requirements-web.txt
    startCommand: gunicorn --chdir desktop_app app:app --bind 0.0.0.0:$PORT
    autoDeploy: trueservices:
  - type: web
    name: post-reminder-desktop
    env: python
    buildCommand: pip install -r desktop_app/requirements-web.txt
    startCommand: gunicorn --chdir desktop_app app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
